#!/usr/bin/env bash
#install ngix and redirect
sudo apt-get update
sudo apt-get install nginx -y
echo -e \
"http {
    root /var/www/html;
    index index.html;
    server {
        listen 80;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
    }
}
events {
}" > /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
sudo service nginx restart
