#!/usr/bin/env bash
#script to configure a new server

sudo apt-get update -y && \
sudo apt-get install -y nginx
sudo chmod 755 /etc/nginx/nginx.conf
echo -e \
"http {
    root /var/www/html;
    index index.html;
    server {
        listen 80;
        location \ {
        }
    }
    add_header X-Served-By "$HOSTNAME";
}
events {
}" | sudo tee /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
