#!/usr/bin/env bash
# Install the load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo sed -i "$ a\ \n\nlisten 145547-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 145547-web-01 54.209.213.214:80 check\n\tserver 145547-web-02 54.160.126.195:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
